***
<b>Author:</b> Raghavendra Tapas

<b>Updated On:</b> May 2021

<b>Context:</b>  Syntax Introduction to `Python Language`

Feel free to reach out to me on __[Twitter](https://twitter.com/raghutapas12)__ for any corrections or additional updates!
***

# Basics of Python

How Python Works?

The python code typed by the programmer, goes to the interpreter (C python, J python, Iron Python, etc). Then the interpreter generates byte code. The byte code runs in Cpython Virtual Machine. The virtual machine then generates machine code which is understood by computers or mobiles.

Taking input from user

Basic stuff to know while printing beautiful outputs 
'\n' = new line character
'\'  = Escape Character
Any thing between ' ' or "  " or can be called a string.
\t = tab or horizontal indentation or 7 spaces

In [241]:
name = input("What is Your Name? \n")
print("Hello "+ name + '! How are you?')

What is Your Name? 
john
Hello john! How are you?


In [242]:
''' This string is on multiple l'ines within three "single quotes on either side. '''



' This string is on multiple l\'ines within three "single quotes on either side. '

<b> raw string </b>tells Python to ignore all formatting within a string, including escape characters.
We create a raw string by putting an r in front of the string, right before the beginning quotation mark:

In [1]:
print(r"Sammy says,\"The balloon\'s color is red.\"")

Sammy says,\"The balloon\'s color is red.\"


## Checking the Data Types

There are numerous data types in python. Each has its own use case. Each consumes a certain amount of memory. In order to write efficient codes, we need to know them. 

Sometimes, we may not be sure about the type of data, a certain function is giving as an output. 

We can check it by using the type function:
type()

<b>Examples</b> are given below:

In [244]:
print(type('Hello World'))

<class 'str'>


In [245]:
print(type(20))

<class 'int'>


In [246]:
print(type(20.5))

<class 'float'>


In [247]:
print(type(1j))

<class 'complex'>


In [248]:
print(type(["apple", "banana", "cherry"]))

<class 'list'>


In [249]:
print(type(("apple", "banana", "cherry")))

<class 'tuple'>


In [250]:
print(type(range(6)))

<class 'range'>


In [251]:
print(type({"name" : "John", "age" : 36}))

<class 'dict'>


In [252]:
print(type({"apple", "banana", "cherry"}))

<class 'set'>


In [253]:
print(type(frozenset({"apple", "banana", "cherry"})))

<class 'frozenset'>


In [254]:
print(type(True))

<class 'bool'>


In [255]:
print(type(b"Hello"))

<class 'bytes'>


In [256]:
print(type(bytearray(5)))

<class 'bytearray'>


In [257]:
print(type(memoryview(bytes(5))))

<class 'memoryview'>


## Operators

In [258]:
x = 2 + 4
print('2 + 4 = ', x)

2 + 4 =  6


In [259]:
x = 2 - 4
print('2 - 4 = ', x)

2 - 4 =  -2


In [260]:
x = 2 * 4
print('2 × 4 = ', x)

2 × 4 =  8


In [261]:
x = 4 / 2
print('4 ÷ 2 = ', x)

4 ÷ 2 =  2.0


In [262]:
x = 4 ** 2
print('4 to the power of 2 = ', x)

4 to the power of 2 =  16


In [374]:
# Quotient
x = 13 % 4
print('Quotient of 13 ÷ 4 = ',x)

x = 252 % 5
print('Quotient of 252 ÷ 5 = ',x)

x = 11 % 6
print('Quotient of 11 ÷ 6 = ',x)

Quotient of 13 ÷ 4 =  1
Quotient of 252 ÷ 5 =  2
Quotient of 11 ÷ 6 =  5


In [264]:
# modulo division operator produces the remainder of an integer division
x = 13 % 4
print('Remainder of 13 ÷ 4 = ', x)

x = 252 % 5
print('Remainder of 252 ÷ 5 = ', x)

x = 11 % 6
print('Remainder of 11 ÷ 6 = ', x)

Remainder of 13 ÷ 4 =  1
Remainder of 252 ÷ 5 =  2
Remainder of 11 ÷ 6 =  5


## BODMAS - Rule

Order of Operation is as follows: -Bracket - of - Division - Multiplication = Addition - Subtraction

Example 1: Find the value of x and y

In [265]:
x = 6 + 3 * 5
y = (6 + 3) * 5
print ('x = ',x)
print ('y = ',y)

x =  21
y =  45


Example 2: Find the value of x = 4 × (10 + 15 / 5 × 4 - 2 × 2)

In [266]:
x = 4 * (10 + 15 / 5 * 4 - 2 * 2)
print (x)

72.0


Example 3: Find the value of 3+3 of 3 ÷ 3 of 3*3

In [267]:
x = 3 + 3 * (3 % 3) * 3 * 3
print('x = ',x)

x =  3


## Conditional Operator Statements

Below listed are some conditions that we can use to execute 
certain blocks of code.

<UL>
<LH>Conditions that can be used: </LH>
    <LI> Equals: a == b
    <LI> Not Equals: a != b
    <LI> Less than: a < b
    <LI> Less than or equal to: a <= b
    <LI> Greater than: a > b
    <LI> Greater than or equal to: a >= b
</UL>

### If-Else Statement

<b>Example 1:</b> Check which number is greater, a or b?

In [268]:
a = 333
b = 200
if b > a:
  print(str(b) + ' is greater than '+ str(a))
else:
    print(str(a) + ' is greater than '+ str(b))

333 is greater than 200


In [269]:
a = 33
b = 200
if b > a:
  print(str(b) + ' is greater than '+ str(a))
else:
    print(str(a) + ' is greater than '+ str(b))

200 is greater than 33


### Nested If-Else Statement

In [270]:
a = 200
b = 33
if b > a:
  print(str(b) + ' is greater than ' + str(a))
elif a == b:
  print(str(b) + ' is equal to ' + str(a))
else:
  print(str(b) + ' is lesser than ' + str(a))

33 is lesser than 200


<b>Note:</b> Try out the other two possible values of a and b. i.e. a == b & a < b

### Switch Statement

Unlike C or other programming languages, we do not have a dedicated switch statement in python. To get around this, we can use dictionary mapping. Dictionary is a type of data structure which is discussed later.

<b>Dictionary</b> is a group of key-value pairs.


<b>Function</b> is a custom rule that we can create in python.





<b> Example:</b>  Function to convert number into string

In [271]:
argument = 1
def numbers_to_strings(argument):
    switch_statement = {
        0: "Zero",
        1: "One",
        2: "Two",
    }
    
    return switch_statement.get(argument, "nothing")

  
# Driver program
if __name__ == "__main__":
    argument=1
    print (numbers_to_strings(argument))

One


### While Loop

In [23]:
#Take input and store it outside the loop
password = input('Type your password: ')

while (password != 'secret'):
  print('Humans have weak memory.')
  password = input('Password incorrect, Retype it: ')
  
else: print('Cool! Make sure you remember it human!')

Type your password:  testing wrong password


Humans have weak memory.


Password incorrect, Retype it:  secret


Cool! Make sure you remember it human!


# Chapter 2: Data Structures

## Strings

### String Concatenation

In [272]:
first_name = 'John'
last_name = 'Doe'
username = first_name + ' ' + last_name
print(username)

John Doe


<b>Note:</b> Long Strings are used to store weird text formats

In [273]:
long_string = '''
o  o vgdetfev
____ afcrwgf
'''
print(long_string)


o  o vgdetfev
____ afcrwgf



## String Indexing

Print the 1st letter of the string that is declared.

In [274]:
string = '0123456789'
print(string[0])

0


Print the mid location of the string

In [275]:
string = '0123456789'
print(string[3:7:])

3456


Print the 4th letter of the string that is declared.

In [276]:
string = '0123456789'
print(string[4])

4


Print letters starting from 1st to 8th letter, excluding 8th letter of the string is printed with interval of 1

In [277]:
string = '0123456789'
print(string[0:8:1])

01234567


Print letters starting from 1st to 8th letter, excluding 8th letter of the string is printed with interval of 2

In [278]:
string = '0123456789'
print(string[0:8:2])

0246


Reverse string indexing. When we do not know the location of the last end of the string.

In [279]:
string = '0123456789'
print(string[::-1])

9876543210


## Type Conversion

In [280]:
#Converting Integer '100' to a string character
a = (str(100))
print(a)
print(type(a))

#Converting String '100' to a Integer character
print(int(str(a)))
print(type(int(str(a))))

100
<class 'str'>
100
<class 'int'>


## Immutability

name = 'raghu'

~~name[0] = hello~~ THAT WON'T WORK

Part of a String cannot be replaced with another value. In other words, strings are not immutable.

## 2.5 Built-In Functions

In [281]:
name = 'john'

print(name.upper())


JOHN


In [282]:
first_name = 'john'
print(first_name.capitalize())


John


In [283]:
first_name = 'JoHn'

print(name.lower())

john


In [284]:
# Replacing words using .replace('word1', 'word2')
quote = 'to be or not to be is the question.'
print_quote = quote.replace('be', 'be busy')
print(print_quote)

to be busy or not to be busy is the question.


## Chapter 3: Data Structures

## 3.1 Lists

Memory allocation starts from 0 and not 1

In [285]:
amazon_cart = ['Notebook', 'Sunglasses','Watch','Laptop']


# Retrieve sunglasses from the list

print(amazon_cart[1])

Sunglasses


### Matrix or 2-Dimensional List

In [19]:
matrix1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

print('\nIndexing items:')
print(matrix1[0][0])
print(matrix1[0][1])

print('\nIndexing arrays:')
print(matrix1[0])
print(matrix1[1])

print('\nReverse indexing:')
print(matrix1[0:2])
print(matrix1[1:3])

print('\nReverse indexing:')
print(matrix1[::-2])
print(matrix1[::-1])


print(matrix1[::2])


Indexing items:
1
2

Indexing arrays:
[1, 2, 3]
[4, 5, 6]

Reverse indexing:
[[1, 2, 3], [4, 5, 6]]
[[4, 5, 6], [7, 8, 9]]

Reverse indexing:
[[7, 8, 9], [1, 2, 3]]
[[7, 8, 9], [4, 5, 6], [1, 2, 3]]
[[1, 2, 3], [7, 8, 9]]


### Lists are Immutable

In [287]:
amazon_cart = ['notebook','1 sunglasses','2 glasses','3 belt','4 bow','5 tie', '6 shoes', '7 toy']
print('Before:\n')
print(amazon_cart)


# Replace notebook by laptop. 
# This can be easily done by assigning using Assignment Operator.

amazon_cart[0] = 'laptop'
print('\nAfter:\n')
print(amazon_cart)

Before:

['notebook', '1 sunglasses', '2 glasses', '3 belt', '4 bow', '5 tie', '6 shoes', '7 toy']

After:

['laptop', '1 sunglasses', '2 glasses', '3 belt', '4 bow', '5 tie', '6 shoes', '7 toy']


### List Slicing

In [288]:
amazon_cart = ['0 notebook','1 sunglasses','2 glasses','3 belt','4 bow','5 tie', '6 shoes', '7 toy']


print(amazon_cart[0:2])
print(amazon_cart[::2])
print(amazon_cart[::-2])

['0 notebook', '1 sunglasses']
['0 notebook', '2 glasses', '4 bow', '6 shoes']
['7 toy', '5 tie', '3 belt', '1 sunglasses']


Printing the length of the list

In [289]:
amazon_cart = ['0 notebook','1 sunglasses','2 glasses','3 belt','4 bow','5 tie', '6 shoes', '7 toy']


print(len(amazon_cart))

8


### List Appending

In [290]:
list = [1,2,3,4,5,6]

#printing before appending operation
print(list)

#appending
list.append(100)

#printing after appending operation
print(list)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 100]


### List Insert

In [291]:
# General Syntax will be:

# list_name.insert(location,item_to_be_inserted)

In [292]:
list = [1,2,3,4,5,6]

#printing before insert operation
print(list)

#inserting
list.insert(3,100)

#printing after insert operation
print(list)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 100, 4, 5, 6]


### List Extend

In [293]:
# General Syntax:
# list_name.extend([item_1,item_2...item_n])


Extend operation takes an iterable as an argument. Anything that can be looped over is an iterable. List, dictionary, etc are all iterables. 

Extend basically takes an entire list or list = [n1, n2,...] as an argument.

In [294]:
list = [1,2,3,4,5,6]

# printing before extend operation
print(list)

# extend operation adds items at the end of the list.
list.extend([99, 100])

# printing after extend operation
print(list)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 99, 100]


### List Pop

In [295]:
list = [1,4,8,10,14,20]

list.pop()

print(list)

[1, 4, 8, 10, 14]


We can specify the index or location of the thing that we want to pop off.

In [296]:
list = [1,4,8,10,14,20]

list.pop(3)

print(list)

[1, 4, 8, 14, 20]


### List Remove

In [297]:
list = [1,4,8,10,14,20]

# remove 4th item from the list
list.remove(4)

print(list)

[1, 8, 10, 14, 20]


### List Indexing

In [298]:
# General Syntax to find the location of an item in the list
# list.index(value, start, stop)

In [299]:
list = ['a','be', 'c', 'd', 'e', 'f', 'd']

print(list.index('be'))

1


### List Clear

Clear methods empties the list.

In [300]:
list = [1,4,8,10,14,20]

list.clear()

print(list)

[]


### List Sorting

In [301]:
list = ['z','a','d','9', '0', '7']
list.sort()
print(list)

['0', '7', '9', 'a', 'd', 'z']


### List Reversing

In [302]:
list = ['z','a','d','9', '0', '7']
list.reverse()
print(list)

['7', '0', '9', 'd', 'a', 'z']


### Sample Problem: Given the list, return a descending order of the list.

In [303]:
list = [1, 9, 6, 3, 7, 5, 6, 4]
list.sort()
list.reverse()
print(list)

[9, 7, 6, 6, 5, 4, 3, 1]


### To check whether an item is present in the list or not

In [304]:
# IN operator returns a boolean answer. True or False
print('i' in 'jji')


list = ['a','b', 'c', 'd', 'e', 'f', 'd', 'xi']

print('d' in list)
print('x' in list)


True
True
False


### Generate Lists

Start: Optional — An integer number that specifies where to start. (Default value is 0)
    
Stop: Required — An integer number that specifies where to stop.
    
Step: Optional — An integer number that specifies how much to increment the number (Default value is 1)

General Syntax: range(start, stop, step)

In [305]:
# Sample Problem: Print every 13th number in the list of 1 to 100.

for i in range(1,100,13):
    print(i)

1
14
27
40
53
66
79
92


In [306]:
for i in range(1,6):
    print(i)

1
2
3
4
5


### Join Built-in Function

In [307]:
#concatenating item in list to string
sentence_1 = ['Hi','my','good','name','is', 'xxxxx']
sentence_2 = ' '.join(sentence_1)
print(sentence_2)

#shorter way of using JOIN method
sentence = ' '.join(['Hi','my','name','is', 'John'])
print(sentence)

Hi my good name is xxxxx
Hi my name is John


### List Unpacking

Since the word 'other' has 5 letters, a list containing 5 numbers will be stored

In [308]:
a,b,c, *other, d = [1,2,3,4,5,6,7,8,9]
print(a)
print(b)
print(other)
print(d)

1
2
[4, 5, 6, 7, 8]
9


## Dictionary

A dictionary is an UNORDERED key-value pair.

In [309]:
dictionary = {
    'key1': 'value 1',
    'key2': 'value 2',
    'c':     1
}

print(dictionary['key1'])
print(dictionary['c'])

value 1
1


In [310]:
dicto = {
'a' : [1,2,3,4],
'b' : 'hello',
'c' : True,
'd' : 576
}
print(dicto['a'])
print(dicto['a'][2])

[1, 2, 3, 4]
3


### GET method

dictionary.get('key', output_this_value_if_key_doesn't_exists)

print(user.get('age', 55))

In [311]:
dictionary = {
    'a': 1,
    'b': 2,
    'c': 3,
    'd': 4
}

dictionary.get('ab', '4+')


'4+'

### Print Entire Dictionary

In [312]:
dictionary = {
    'a': 1,
    'b': 2,
    'c': 3,
    'd': 4
}

print(dictionary.items())


dict_items([('a', 1), ('b', 2), ('c', 3), ('d', 4)])


### Clear Dictionary

Clears all the keys and values

In [20]:
dictionary = {
    'a': 1,
    'b': 2,
    'c': 3,
    'd': 4
}

print(dictionary.clear()) 

None


### Checking the presence of a key in a dictionary

In [ ]:
dictionary = {
    'a': 1,
    'b': 2,
    'c': 3,
    'd': 4
}

print('d' in dictionary)
print('e' in dictionary)

### Deleting a Key-Value Pair

In [ ]:
dictionary = {
    'a': 1,
    'b': 2,
    'c': 3,
    'd': 4
}
dictionary.pop('a')

# Printing to check what the dictionary contains
print(dictionary.items())

# Method 2 of checking whether 'a': 1, key-value pair exists or not
print('a' in dictionary)

### Update a Dictionary value

In [ ]:
dictionary = {
    'a': 1,
    'b': 2,
    'c': 3,
    'd': 4
}
dictionary.update({'a' : 5})

print(dictionary.items())

## Tuple

Tuple is a non-flexible list. Cannot be modified, sorted, reversed or re-arranged.

General Syntax: tuple_name = (object_1,object_2, object_3,...)


### Tuple Indexing

In [ ]:
tuple = (1,2,3,4,5,5,6,7,8,8,8,5)
print(tuple[2])

### Tuple Search

In [ ]:
tuple = (1,2,3,4,5,5,6,7,8,8,8,5)
print('5' in tuple)

### Tuple Searching numbers

In [ ]:
tuple = (1,2,3,4,5,5,6,7,8,8,8,5)
print(2 in tuple)

### Finding length of tuple

In [ ]:
tuple = (1,2,3,4,5,5,6,7,8,8,8,5)
print(len(tuple))

### Counting the Number of times an object has repeated

In [ ]:
tuple = (1,2,3,4,5,5,6,7,8,8,8,5)
print(tuple.count(5))

### Finding the index number of an object in a Tuple

In [ ]:
tuple = (1,2,3,4,5,5,6,7,8,8,8,5)
print(tuple.index(5))

In [ ]:
# Interesting Example: 

tuple_matrix = (
[1,2,3,4],
[5,6,7,8],
[9,1,2,3],
[4,5,6,7])

print(tuple_matrix[0][0])
print(tuple_matrix[0][1])

## Set

Set is an un-ordered collection of unique objects. 

Can be used to find out unique or distinct objects in a list.

### Printing

In [ ]:
my_set = {100,2,3,4,5,5,6,7,8,2,3,2,1}
print(my_set)

### Length of a set

In [ ]:
my_set = {100,2,3,4,5,5,6,7,8,2,3,2,1}
print(len(my_set))

### Search a set

In [240]:
my_set = {100,2,3,4,5,5,6,7,8,2,3,2,1}
print(1 in my_set)

True


### Adding an object to a set

In [319]:
my_set = {2,3,2,1}
my_set.add(100)
my_set.add(23)
print(my_set)

{1, 2, 3, 100, 23}


### Sorting a set

In [333]:
my_set = {100,2,3,4,5,5,6,7,8,2,3,2,1}
print(sorted(my_set))

[1, 2, 3, 4, 5, 6, 7, 8, 100]


### Converting set to a list

In [2]:
my_set = set({1, 4, 3, 5})
 
print(list(my_set))

## Note: The error exists only in Jupyter environment


[1, 3, 4, 5]


### Printing Key Value pair

In [353]:
user_1 = {
'name': 'Icefish',
'age': 5,
'can_swim': True
}

for key, value in user_1.items():
    key = str(key)
    value = str(value)
    print(key + ' ' + value)

name Icefish
age 5
can_swim True


## Functions

Throughout programs, we encounter situations where in we might need to use the same chunk of code over and over. So we use functions. To not repeat ourselves.

In [29]:
def say_hello():
    print('Hello!')
    print('This is a function to print 4 sentences!')
    print('This is a function to print 4 sentences!')
    print('This is a function to print 4 sentences!')

#calling the function with brackets
say_hello()

Hello!
This is a function to print 4 sentences!
This is a function to print 4 sentences!
This is a function to print 4 sentences!


### Parameters and Arguments

In [37]:
#parameters

def say_hello(first_name, last_name):
    print(f'Helloooo {first_name} isn\'t it exciting to use functions, {last_name}')
#arguments
say_hello('argument-1','argument-2?')
say_hello('Tiger','Woods?')
say_hello('Bond','James?')

Helloooo argument-1 isn't it exciting to use functions, argument-2?
Helloooo Tiger isn't it exciting to use functions, Woods?
Helloooo Bond isn't it exciting to use functions, James?


<b> Problem 1:</b> Check if the number is even or odd using functions.

In [47]:
num = int(input('Input a number: '))

def even(num):
    # This function checks if a given input is even or not.
    if num % 2 == 0:
        print(f'The input number: {num} = Even')
    else:
        print(f'The input number: {num} = Odd')

even(num)

Input a number:  5


The input number: 5 = Odd


<b>Problem 2:</b> Take a list as an input and display only even numbers present in that list.

Also display the highest even number.

In [49]:
# function to append only even numbers into an empty list
def highest_even(list_1):
  even_list = []
  for number in list_1:
    if number % 2 == 0:
      even_list.append(number)

# Built-in Function
  a = max(even_list)
 
  print(f'List of even numbers {even_list}\n')
  print(f'Highest even number is \'{a}\'')

# calling the function
highest_even([8,10,29,49,2,5,6,7,8])

List of even numbers [8, 10, 2, 6, 8]

Highest even number is '10'


# NumPy Library

We use numpy library as it is computationally faster than list and consumes less memory technically. Plus it is feature rich.

Below mentioned are 14 problems to help practice matrix slicing.
Problem 1: Print 1 2 3

In [204]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# Y AXIS, X AXIS
# print(dimension_1-start: dimension_1-stop, dimension_2-start, dimension_2-stop])
print(A[0:1, 0:3])


[[1 2 3]]


Problem 2: Print 4 5 6

In [186]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


print(A[1:2, 0:3])

[[4 5 6]]


Problem 3: Print 7, 8, 9

In [187]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A[2:3, 0:3])

[[7 8 9]]


Problem 4: Print 123 and 456

In [188]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A[0:2, 0:3])

[[1 2 3]
 [4 5 6]]


Problem 5: Print 456 & 567

In [191]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A[1:3, 0:3])

[[4 5 6]
 [7 8 9]]


Problem 6: Print first column: 147

In [193]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A[0:3,0:1])

[[1]
 [4]
 [7]]


Problem 7: Print mid column

In [194]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A[0:3,1:2])

[[2]
 [5]
 [8]]


Problem 8: Print last column: 369

In [195]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A[0:3,2:3])

[[3]
 [6]
 [9]]


Problem 9: Print first two columns

In [196]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A[0:3,0:2])

[[1 2]
 [4 5]
 [7 8]]


Problem 10: Print second and third columns

In [197]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A[0:3,1:3])

[[2 3]
 [5 6]
 [8 9]]


Problem 11: Print 12 and 45

In [198]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A[0:2, 0:2])

[[1 2]
 [4 5]]


Problem 12: Print 56 and 89

In [199]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A[1:3, 1:3])

[[5 6]
 [8 9]]


Problem 13: From the second element, slice elements from index 1 to index 4 (not included):

In [168]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


Problem 14: From both elements, return index 2:

In [169]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


## Matrix Operations in NumPy

The +, -, *, % or // and all other operators can be easily used if we import numpy library.

In [201]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = A * 5

print('B = ')
print(B)

print('A = ')
print(A)

B = 
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Pandas

In [4]:
import pandas as pd

# 2 main data types
# columns - 1D
series = pd.Series(["BMW", "Toyota", "Honda"])
colors = pd.Series(["Red", "Green", "Silver"])

# DataFrame = 2-D
carData = pd.DataFrame({"Car maker": series, "Colour": colors})
carData

Car maker  Colour
0       BMW     Red
1    Toyota   Green
2     Honda  Silver

Note: Rather than creating data from series we can import data.

# Easy Level Problems

<b>Problem 1:</b> Taking year of birth and print the age as output.

Note: It is to be noted here that you can only concatenate two string. You cannot concatenate a string with a number.

In [22]:
import datetime
x = datetime.datetime.now()
dob = input('Type the year of birth please? \n')
now = '%Y'
age = int(x.year) - int(dob)
print('Your age is ' + str(age))

Type the year of birth please? 
2009
Your age is 12


<br>
<b>Problem 2:</b> Take username and password from the user. 
    
Hello #username, your password #Password (first two characters must be printed as is and the rest should all be stars) has # characters.

In [29]:
username = input("Type Username: \n")
password = input("Type Password: \n")
length = len(password) - 2

print('Hello ' + username + ", your password is " + password[0:2:1] + length * '*')

Type Username: 
john
Type Password: 
doe
Hello john, your password is do*


<br>
<b>Problem 3:</b> Display the image below to the right hand side, where the 0 is going to be ' ', and the 1 is going to be '*'. This will reveal an image!

In [205]:
picture = [
  [0,0,0,1,0,0,0],
  [0,0,1,1,1,0,0],
  [0,1,1,1,1,1,0],
  [1,1,1,1,1,1,1],
  [0,0,0,1,0,0,0],
  [0,0,0,1,0,0,0]
]

for row in picture:
  for pixel in row:
    if pixel == 0:
      print(' ', end='')
    else:
      print('*', end='')
  print('k')

   *   k
  ***  k
 ***** k
*******k
   *   k
   *   k


# Medium Level Problems

## 1. Decimel to Binary Conversion

Example 1: Convert decimel number 34 to binary number using python

In [373]:
def decimelToBinary(x):
    if x > 1 :
        y = x // 2
        print(y % 2)


# Take input from user
x = input('Enter a decimel number: ')

# Convert to integer
x = int(x)

decimelToBinary(x)

Enter a decimel number: 7
1
